sudo: false

language: node_js

node_js:
  - '6'
  - '7'
  - '8'

git:
  depth: 1

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
