sudo: false

language: node_js

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

git:
  depth: 1

branches:
  only:
  - master
  - /^greenkeeper-/

notifications:
  email: false

before_install:
  - npm install -g npm
  - npm -v
after_success: npm run coverage
